#!/bin/sh
SESSION_ID=276B7A62-B6E5-4CED-AB14-6CED4C26BE7C
USER_ID=$1
if [ -z $USER_ID ] ; then
	USER_ID=`uuidgen`
fi
echo $USER_ID
curl --request POST --data-binary @../resources/training/arm3.dat http://localhost:12552/exercise/$USER_ID/$SESSION_ID
echo $USER_ID | pbcopy
