#!/bin/sh
USER_ID=$1
if [ -z $USER_ID ] ; then
	USER_ID=`uuidgen`
fi
echo $USER_ID
curl --request POST --data-binary @../resources/training/arm3.dat http://localhost:12552/exercise/$USER_ID
echo $USER_ID | pbcopy
